services:
  spring-boot-app:
    build: .
    ports:
      - "${APPLICATION_HOST_PORT}:${APPLICATION_CONTAINER_PORT}"
    depends_on:
        db:
          condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:${DATABASE_CONTAINER_PORT}/${DATABASE_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USER}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      APPLICATION_PORT: ${APPLICATION_CONTAINER_PORT}
    restart: on-failure

  db:
    image: mysql:9.4.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 30s
    ports:
      - "${DATABASE_HOST_PORT}:${DATABASE_CONTAINER_PORT}"

volumes:
  db-data:

